import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Пользователь',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    {
      name: 'Диана',
      email: 'diana@mail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    {
      name: 'Алина',
      email: 'alina@mail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Кресло Nils',
      slug: '1',
      category: 'Кресла',
      image: '/images/Нилс.jpg',
      price: 17990,
      brand: 'Nils',
      rating: 40,
      numReviews: 0,
      countInStock: 20,
      description:
        'Габариты: ширина 58 см, высота 84 см, глубина 58 см, ширина сиденья 40 см, высота сиденья 45 см, глубина сиденья 40 см, высота подлокотников 19 см',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Кресло Amsterdam',
      slug: '2',
      category: 'Кресла',
      image: '/images/Амстердам.jpg',
      price: 33640,
      brand: 'Amsterdam',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'Габариты: ширина 86 см, высота 85 см, глубина 95 см, ширина сиденья 58 см, высота сиденья 43 см, глубина сиденья 76 см, высота подлокотников 66 см',
    },
    {
      name: 'Диван Loa 2-местный',
      slug: '3',
      category: 'Диваны',
      image: '/images/Лоа.jpg',
      price: 40930,
      brand: 'Loa',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'Габариты: ширина 175 см, высота 85 см, глубина 80 см, ширина сиденья 145 см, высота сиденья 45 см, глубина сиденья 40 см, высота подлокотников 40 см',
    },
    {
      name: 'Диван Peterhof',
      slug: '4',
      category: 'Диваны',
      image: '/images/Питерхоф.jpg',
      price: 51890,
      brand: 'Peterhof',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'Габариты: ширина 282 см, высота 88 см, глубина 170 см, ширина сиденья 235 см, высота сиденья 45 см, глубина сиденья 75 см, высота подлокотников 64 см',
    },
    {
      name: 'Диван Kona',
      slug: '5',
      category: 'Диваны',
      image: '/images/Кона.jpg',
      price: 47560,
      brand: 'Kona',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'Габариты: ширина 270 см, высота 87 см, глубина 155 см, ширина сиденья 225 см, высота сиденья 45 см, глубина сиденья 60 см, высота подлокотников 60 см',
    },
    {
      name: 'Кресло Lexi',
      slug: '6',
      category: 'Стулья',
      image: '/images/Лекси.jpg',
      price: 9900,
      brand: '',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'Габариты: ширина 58 см, высота 84 см, глубина 58 см, ширина сиденья 40 см, высота сиденья 45 см, глубина сиденья 40 см, высота подлокотников 19 см',
    },
    {
      name: 'Стул Frank',
      slug: '7',
      category: 'Стулья',
      image: '/images/Франк.jpg',
      price: 1495,
      brand: 'Frank',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'Габариты: ширина 47 см, высота 82 см, глубина 51 см, ширина сиденья 37 см, высота сиденья 45 см, глубина сиденья 40 см, высота спинки 41 см',
    },
    {
      name: 'Письменный стол Кассия',
      slug: '8',
      category: 'Столы',
      image: '/images/Кассия.jpg',
      price: 24860,
      brand: 'Кассия',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'Столешница: ЛДСтП 22 мм. Каркас: металлическая рама, ЛДСтП 16 мм. Фасад: МДФ 19 мм + пленка ПВХ. Задняя стенка: ЛДСтП 16 мм. Кромка: ABS 0,5-1 мм. Направляющие: шариковые полного выдвижения, с доводчиками. Опоры: металл чёрного цвета. Нагрузка: на дно ящика — 5 кг, на столешницу — до 40 кг.',
    },
    {
      name: 'Стол журнальный Rond',
      slug: '9',
      category: 'Столы',
      image: '/images/Ронд.jpg',
      price: 5500,
      brand: 'Rond',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description: 'Габариты: высота 43 см, диаметр 59 см',
    },
    {
      name: 'Шкаф Сириус',
      slug: '10',
      category: 'Шкафы',
      image: '/images/Сириус.jpg',
      price: 20999,
      brand: 'Сириус',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description: 'Габариты: ширина 117 см, высота 190 см, глубина 50 см',
    },
    {
      name: 'Шкаф-купе Корсо',
      slug: '11',
      category: 'Шкафы',
      image: '/images/Корсо.jpg',
      price: 48630,
      brand: 'Корсо',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'Корпус и полки: ЛДСтП 16 мм, крышка и дно — цельные. Фасады: ЛДСтП 16 мм. Задняя стенка: ХДФ. Кромка: ПВХ 1 мм. Фурнитура: система «Интал» (алюминиевый ходовой профиль, комплектующие). Ручки: алюминий, со шлегелем (защитная щетка). Крепления для полок: полкодержатели скрытого типа — флипперы. Максимальная нагрузка на полки: 25 кг.',
    },
  ],
}

export default data
